app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path: /register
    controller: AppBundle:Auth:register
    methods: POST

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
login_check:
    path:     /login_check
    methods:  [POST]