app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path: /register
    controller: AppBundle:Auth:register
    methods: POST

api:
    path: /api
    controller: TestBundle:Api\Post:getPost

login_check:
    path:     /login_check
    methods:  [POST]