app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check

register:
    path: /register
    controller: Appbundle\Controller\AuthController::register
    methods: POST

api:
    path: /api
    controller: Appbundle\Controller\AuthController::api